language: python
cache: pip
python:
  - '2.7'
env:
  - TOXENV=pep8
addons:
  apt:
    packages:
before_install:
   # Work around for installation issue
   # https://github.com/certbot/certbot/issues/2850
   - sudo apt-get update
   - sudo apt-get install python-software-properties
   - sudo apt-get install apt-file
   - sudo apt-file update
   - sudo apt-get install software-properties-common
  # get Conda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
    # install wxPython 3.0.0.0
  - conda install -c https://conda.anaconda.org/travis wxpython
script:
  - tox
  - py.test --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  # - cat /home/travis/build/Ebag333/Pyfa/.tox/pep8/log/pep8-0.log
