language: python
python:
  - '2.7'
env:
  - TOXENV=pep8
addons:
  apt:
    packages:
      # for wxPython:
      - python-wxgtk3.0
      - python-wxtools
      - python-wxversion
      - wx3.0-doc
      - wx3.0-examples
      - wx3.0-headers
      - wx3.0-i18n
before_install:
  - pip install -U tox
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
script:
  - tox
  - py.test --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
